
name: No Response Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check token permissions
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Event: $GITHUB_EVENT_NAME"
      
      - name: Try to create an issue comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${GITHUB_REPOSITORY}/issues/${{ github.event.pull_request.number }}/comments \
            -f body="This is a test comment from the workflow" \
            -H "Accept: application/vnd.github+json"
